# Generated by Django 5.2.4 on 2026-03-28 14:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Search engine summary', max_length=160),
        ),
    ]
